### ISSUE TITLE
Iteration-03 milestone done: organize bug bash and wrap up Iteration-03

### ISSUE THREAD

**Issue by jfomhover** [Azure-Samples/azure-ml-federated-learning#126]
Once all current issues of the Iteration-02 milestone are closed:
- [x] organize bug bash with docs as only self-service source
- [x] file all issues under the milestone
- [x] redirect all "deploy to azure" links to point to main branch instead of release branch
- [x] triage + fix all issues that are needed for Iteration-02
- [x] document the changes in the CHANGELOG
- [x] make sure CI/CD runs and completes
- [x] merge into main
- [x] close the milestone.
- [x] issue a new tag for this release, with a fancy description of the changes

**Comment by jfomhover** [comment]
In https://github.com/Azure-Samples/azure-ml-federated-learning/blob/release-sdkv2-iteration-03/docs/provisioning/orchestrator_open.md

path to template is wrong, use fl_pairs instead

**Comment by jfomhover** [comment]
Add annotations in the config.yaml explaining where users should put their orch/silo settings.

**Comment by jfomhover** [comment]
For typical failure of permissions during training, add a troubleshooting guide with screenshot explaining if failure for access denied during training, maybe check permissions of silo compute on orchestrator storage.

**Comment by jfomhover** [comment]
Clarify parameters "existing *" in exisitng storage tyutorial

**Comment by jfomhover** [comment]
Add a simple way to set the permissions RBAC between silo and orchestrator
