### ISSUE TITLE
Iteration-04 milestone done: organize bug bash and wrap up Iteration-04

### ISSUE THREAD

**Issue by thomasp-ms** [Azure-Samples/azure-ml-federated-learning#176]
Once all current issues of the [Iteration-04 milestone](https://github.com/Azure-Samples/azure-ml-federated-learning/milestone/4) are closed:
- [x] organize bug bash with docs as only self-service source
- [x] file all issues under the milestone
- [x] redirect all "deploy to azure" links to point to main branch instead of release branch
- [x] triage + fix all issues that are needed for Iteration-04
- [x] document the changes in the CHANGELOG
- [x] make sure CI/CD runs and completes
- [x] merge into main
- [x] close the milestone.
- [x] issue a new tag for this release, with a fancy description of the changes

The list was adapted from [this issue from the previous iteration](https://github.com/Azure-Samples/azure-ml-federated-learning/issues/126) but is not set in stone.

**Comment by garg-amit** [comment]
https://github.com/Azure-Samples/azure-ml-federated-learning/releases/tag/v0.3.0
