### ISSUE TITLE
MVP milestone done: organize bug bash and wrap up MVP

### ISSUE THREAD

**Issue by jfomhover** [Azure-Samples/azure-ml-federated-learning#51]
Once all current issues of the MVP milestone are closed:
- [ ] organize bug bash with docs as only self-service source
- [ ] file all issues under the milestone
- [ ] triage + fix all issues that are needed for MVP
- [ ] close the milestone.

**Comment by thomasp-ms** [comment]
@garg-amit and I have been bugbashing each other's part, and we are confident we are good to release. For the next iteration, we anticipate we will do an "official" AIMS bug bash
