### ISSUE TITLE
Iteration-02 milestone done: organize bug bash and wrap up Iteration-02

### ISSUE THREAD

**Issue by thomasp-ms** [Azure-Samples/azure-ml-federated-learning#52]
Once all current issues of the Iteration-02 milestone are closed:
- [x] organize bug bash with docs as only self-service source
- [x] file all issues under the milestone
- [x] triage + fix all issues that are needed for Iteration-02
- [x] document the changes in the CHANGELOG
- [x] close the milestone.
- [x] issue a new tag for this release, with a fancy description of the changes
